[package]
name = "shoot-proto"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24"

sdl2 = "0.35"
piston_window = "0.128"
pistoncore-sdl2_window = "0.68"
# once_cell = "1.17"
